config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  root 'projects#index'

  resources :projects
  resources :users

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :website_user

  private
  def website_user
    User.first
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Luke Escobar's Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "shared/header" %>
<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<div class='projects-container'>
  <% @projects.each do |project| %>
    <div class='project'>
      <%= link_to(project) do %>
        <div class='project-head-divison'>
        </div>
        <div class='project-avatar'>
          <%= image_tag(project.avatar) %>
        </div>
        <div class='project-desc'>
          <div class='project-title'>
            <%= project.title.capitalize %>
          </div>
          <div class='project-year'>
            <%= project.year %>
          </div>
          <div class='project-subtitle'>
            <%= project.subtitle %>
          </div>
        </div>
        <div class='project-foot-divison'>

        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class='projects-show'>
  <div class='show-header'>
    <div class='project-name'>
      <%= @project.title %>
    </div>
    <!-- <div class='navigation'>
      Previous
      Next
    </div> -->
  </div>

  <div class='project-division'> </div>

  <div class='project-text'>
    <%= @project.description %>
  </div>

  <div class='project-images'>
  </div>

</div>

app/views/shared/_header.html.erb
<div class="navbar">
  <div class='website-owner'>
    <%= website_user.name %>
  </div>
  <div class='website-links'>
    <ul>
      <li> <%= link_to "Work", projects_path %> </li>
      <li> <%= link_to "Resume", root_path %> </li>
      <li> <%= link_to "About", user_path(website_user.id) %> </li>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>